import matplotlib.pyplot as plt
import pandas as pd
import sys
plt.style.use('../thesis_style.mplstyle')

if len(sys.argv[1:]) != 2:
    print("Specify at minimum two file names")
    quit()

base_file1 = ".".join(sys.argv[1].split(".")[0:-1])
base_file2 = ".".join(sys.argv[2].split(".")[0:-1])

def read_bag_file(file_name_str: str):
    df = pd.read_csv(file_name_str, header=None, skipinitialspace=True)

    ##### Parts of the marked script has ben generated by generative AI
    # indexes
    ts_cols = [0, 1]
    name_start = 3  # first "name" column index
    # extract name columns from first row (right neighbors)
    first = df.iloc[0].tolist()
    # build list of (name_col_idx, value_col_idx) pairs
    pairs = [(i, i+1) for i in range(name_start, df.shape[1], 2)]

    # column names from first row's name columns (value is right neighbor)
    col_names = [first[val_idx].strip() for val_idx,_  in pairs]

    out = pd.DataFrame()
    out['timestamp']= df.iloc[:,ts_cols[0]]+df.iloc[:,ts_cols[1]]/1000000000.0

    # - for each pair, take the value-column for all rows and name it after the first row's name
    for (_, val_idx), name in zip(pairs, col_names):
        out[name] = df.iloc[:, val_idx]
    #### END AI

    return out

df1 = read_bag_file(sys.argv[1])
df2 = read_bag_file(sys.argv[2])

sampling_duration = df1['timestamp'].iloc[-1]-df1['timestamp'].iloc[0]
print(f'Sampling Duration, set 1: {sampling_duration}')
sampling_duration = df2['timestamp'].iloc[-1]-df2['timestamp'].iloc[0]
print(f'Sampling Duration, set 1: {sampling_duration}')

print(f'STD (controller_manager.total_time), set 1: {df1['controller_manager.total_time'].std()}')
print(f'STD (controller_manager.total_time), set 2: {df2['controller_manager.total_time'].std()}')

print(f'STD (controller_manager.update_time), set 1: {df1['controller_manager.update_time'].std()}')
print(f'STD (controller_manager.update_time), set 2: {df2['controller_manager.update_time'].std()}')

print(f'STD (controller_manager.read_time), set 1: {df1['controller_manager.read_time'].std()}')
print(f'STD (controller_manager.read_time), set 2: {df2['controller_manager.read_time'].std()}')

print(f'STD (controller_manager.write_time), set 1: {df1['controller_manager.write_time'].std()}')
print(f'STD (controller_manager.write_time), set 2: {df2['controller_manager.write_time'].std()}')


# Plot
binwidth=1
plt.figure(0)
col = 'controller_manager.read_time'
plt.hist(df1[col], bins=range(int(min(df1[col])), int(max(df1[col]))+binwidth, binwidth),label=f'non-RT (mean: {df1[col].mean():.2f} max: {df1[col].max():.2f})',histtype="step", density=True)
plt.hist(df2[col], bins=range(int(min(df2[col])), int(max(df2[col]))+binwidth, binwidth),label=f'RT (mean: {df2[col].mean():.2f} max: {df2[col].max():.2f})',histtype="step", density=True)
plt.ylabel(r'Samples (norm.)')
plt.xlabel(r'$t_{read}$ [$\mu $s]')
plt.legend(loc='upper center', bbox_to_anchor=(0.35, -0.3),
          fancybox=True, ncol=1)
plt.tight_layout()
plt.savefig(f"{base_file1}_{base_file2}_read.pdf", bbox_inches='tight')
plt.savefig(f"{base_file1}_{base_file2}_read.png", bbox_inches='tight')
plt.show()

plt.figure(0)
col = 'controller_manager.write_time'
plt.hist(df1[col], bins=range(int(min(df1[col])), int(max(df1[col]))+binwidth, binwidth),label=f'non-RT (mean: {df1[col].mean():.2f} max: {df1[col].max():.2f})',histtype="step", density=True)
plt.hist(df2[col], bins=range(int(min(df2[col])), int(max(df2[col]))+binwidth, binwidth),label=f'RT (mean: {df2[col].mean():.2f} max: {df2[col].max():.2f})',histtype="step", density=True)
plt.ylabel(r'Samples (norm.)')
plt.xlabel(r'$t_{write}$ [$\mu $s]')
plt.legend(loc='upper center', bbox_to_anchor=(0.35, -0.3),
          fancybox=True, ncol=1)
plt.tight_layout()
plt.savefig(f"{base_file1}_{base_file2}_write.pdf", bbox_inches='tight')
plt.savefig(f"{base_file1}_{base_file2}_write.png", bbox_inches='tight')
plt.show()

plt.figure(0)
col = 'controller_manager.total_time'
plt.hist(df1[col], bins=range(int(min(df1[col])), int(max(df1[col]))+binwidth, binwidth),label=f'non-RT (mean: {df1[col].mean():.2f} max: {df1[col].max():.2f})',histtype="step", density=True)
plt.hist(df2[col], bins=range(int(min(df2[col])), int(max(df2[col]))+binwidth, binwidth),label=f'RT (mean: {df2[col].mean():.2f} max: {df2[col].max():.2f})',histtype="step", density=True)
plt.ylabel(r'Samples (norm.)')
plt.xlabel(r'$t_{loop}$ [$\mu $s]')
plt.legend(loc='upper center', bbox_to_anchor=(0.35, -0.3),
          fancybox=True, ncol=1)
plt.tight_layout()
plt.savefig(f"{base_file1}_{base_file2}_total.pdf", bbox_inches='tight')
plt.savefig(f"{base_file1}_{base_file2}_total.png", bbox_inches='tight')
plt.show()