import matplotlib.pyplot as plt
import pandas as pd
import sys
plt.style.use('../thesis_style.mplstyle')

if len(sys.argv[1:]) != 1:
    print("Specify a file name")
    quit()

base_file = ".".join(sys.argv[1].split(".")[0:-1])
df = pd.read_csv(sys.argv[1], header=None, skipinitialspace=True)

##### Parts of the marked script has ben generated by generative AI
# indexes
ts_cols = [0, 1]
name_start = 3  # first "name" column index
# extract name columns from first row (right neighbors)
first = df.iloc[0].tolist()
# build list of (name_col_idx, value_col_idx) pairs
pairs = [(i, i+1) for i in range(name_start, df.shape[1], 2)]

# column names from first row's name columns (value is right neighbor)
col_names = [first[val_idx].strip() for val_idx,_  in pairs]

out = pd.DataFrame()
out['timestamp']= df.iloc[:,ts_cols[0]]+df.iloc[:,ts_cols[1]]/1000000000.0

# - for each pair, take the value-column for all rows and name it after the first row's name
for (_, val_idx), name in zip(pairs, col_names):
    out[name] = df.iloc[:, val_idx]

# print(out)
#### END AI

# Sampling duration:

sampling_duration = out['timestamp'].iloc[-1]-out['timestamp'].iloc[0]
print(sampling_duration)

# Plot
binwidth=1
plt.figure(0)
col = 'bioscara.stats/read_cycle/execution_time/current_value'
plt.hist(out[col], bins=range(int(min(out[col])), int(max(out[col]))+binwidth, binwidth),label=f'arm (mean: {out[col].mean():.2f} max: {out[col].max():.2f})',histtype="step")
col = 'controller_manager.read_time'
plt.hist(out[col], bins=range(int(min(out[col])), int(max(out[col]))+binwidth, binwidth),label=f'CM (mean: {out[col].mean():.2f} max: {out[col].max():.2f})',histtype="step")
plt.ylabel(r'Samples')
plt.xlabel(r'$t_{read}$ [$\mu $s]')
plt.legend(loc='upper center', bbox_to_anchor=(0.4, -0.3),
          fancybox=True, ncol=1)
plt.tight_layout()
plt.savefig(f"{base_file}_read.pdf", bbox_inches='tight')
plt.savefig(f"{base_file}_read.png", bbox_inches='tight')
plt.show()

plt.figure(1)
col = 'bioscara.stats/write_cycle/execution_time/current_value'
plt.hist(out[col], bins=range(int(min(out[col])), int(max(out[col]))+binwidth, binwidth),label=f'arm (mean: {out[col].mean():.2f} max: {out[col].max():.2f})',histtype="step")
col = 'controller_manager.write_time'
plt.hist(out[col], bins=range(int(min(out[col])), int(max(out[col]))+binwidth, binwidth),label=f'CM (mean: {out[col].mean():.2f} max: {out[col].max():.2f})',histtype="step")
plt.ylabel(r'Samples')
plt.xlabel(r'$t_{write}$ [$\mu $s]')
plt.legend(loc='upper center', bbox_to_anchor=(0.4, -0.3),
          fancybox=True, ncol=1)
plt.tight_layout()
plt.savefig(f"{base_file}_write.pdf", bbox_inches='tight')
plt.savefig(f"{base_file}_write.png", bbox_inches='tight')
plt.show()

plt.figure(2)
col1 = 'bioscara.stats/write_cycle/execution_time/current_value'
col2 = 'bioscara.stats/read_cycle/execution_time/current_value'
sum = out[[col1,col2]].sum(axis=1)
plt.hist(sum, bins=range(int(min(sum)), int(max(sum))+binwidth, binwidth),label=f'arm (mean: {sum.mean():.2f} max: {sum.max():.2f})',histtype="step")
col = 'controller_manager.total_time'
plt.hist(out[col], bins=range(int(min(out[col])), int(max(out[col]))+binwidth, binwidth),label=f'CM (mean: {out[col].mean():.2f} max: {out[col].max():.2f})',histtype="step")
plt.ylabel(r'Samples')
plt.xlabel(r'$t_{sum}$ [$\mu $s]')
plt.legend(loc='upper center', bbox_to_anchor=(0.4, -0.3),
          fancybox=True, ncol=1)
plt.tight_layout()
plt.savefig(f"{base_file}_total.pdf", bbox_inches='tight')
plt.savefig(f"{base_file}_total.png", bbox_inches='tight')
plt.show()