/* Author: sbstorz */

#ifndef BIOSCARA_RVIZ_PANEL_HPP_
#define BIOSCARA_RVIZ_PANEL_HPP_

#include <QLabel>
#include <QPushButton>
#include <unordered_map>
#include <vector>

#include <rviz_common/panel.hpp>
#include <rviz_common/ros_integration/ros_node_abstraction_iface.hpp>
#include "controller_manager_msgs/msg/controller_manager_activity.hpp"
#include "controller_manager_msgs/msg/named_lifecycle_state.hpp"
#include "controller_manager_msgs/srv/list_controllers.hpp"
#include "controller_manager_msgs/srv/set_hardware_component_state.hpp"
#include "controller_manager_msgs/srv/switch_controller.hpp"
#include "controller_manager_msgs/srv/configure_controller.hpp"
#include "control_msgs/msg/dynamic_joint_state.hpp"
#include "control_msgs/msg/dynamic_interface_group_values.hpp"

namespace Ui
{
  class BioscaraUI;
}

namespace bioscara_rviz_plugin
{
  using namespace controller_manager_msgs::msg;
  using namespace controller_manager_msgs::srv;
  using namespace control_msgs::msg;

  /**
   * @brief RViz Panel to control the hardware specific functions of the Bioscara robot.
   *
   * Through the panel it is possible to modify the robot's hardware's and controller states and to execute the homing procedures.
   */
  class BioscaraPanel : public rviz_common::Panel
  {
    Q_OBJECT
  public:
    /**
     * @brief Construct a new Bioscara Panel object
     *
     * Creates a new #ui_ object from the ui object autogenerated from the
     *  "bioscara_rviz_plugin_frame.ui". This object contains
     * all UI elements.
     * Each button gets assigned a callback function.
     * @param parent
     */
    explicit BioscaraPanel(QWidget *parent = 0);

    /**
     * @brief Destroy the Bioscara Panel object
     *
     */
    ~BioscaraPanel() override;

    /**
     * @brief Automatically invoked by the RViz parent class. Initializes the panel.
     *
     * Retrieves the pointer to the parent node and saves it in #node_.
     * This node and its executor is used for all clients and publishers.
     *
     * Additionally a the #prune_timer_ is created which periodically cleans all dangling service requests.
     * All subscribers, publishers and clients are created and saved in their corresponding handler.
     * Also the #controller_states_state and #hardware_states_ state maps are prepopulated by invoking prepopulate_state_map()
     */
    void onInitialize() override;

  protected:
    /**
     * @brief Pointer to the parent node. Used for access to the executor.
     */
    rclcpp::Node::SharedPtr node_;

    /**
     * @brief Subscription to the the controller_manager state publisher
     *
     * Used to retrieve information about hardware and controller state changes.
     *
     */
    rclcpp::Subscription<ControllerManagerActivity>::SharedPtr cm_state_subsription_;

    /**
     * @brief Subscription to the the joint state publisher state publisher.
     *
     * Uses the "/dynamic_joint_states" to receive updates of all joints states.
     *
     */
    rclcpp::Subscription<DynamicJointState>::SharedPtr joint_state_subsription_;

    /**
     * @brief Publisher to send commands to the homing_controller.
     *
     * Used to start and stop homing of joints.
     *
     */
    rclcpp::Publisher<DynamicInterfaceGroupValues>::SharedPtr homing_publisher_;

    /**
     * @brief Service client to the "/controller_manager/switch_controller" service.
     *
     * Used to request activation and deactivation of controllers.
     *
     */
    rclcpp::Client<SwitchController>::SharedPtr switch_controller_client_;

    /**
     * @brief Service client to the "/controller_manager/configure_controller" service.
     *
     * Used to request configuration and cleanup of controllers.
     *
     */
    rclcpp::Client<ConfigureController>::SharedPtr configure_controller_client_;

    /**
     * @brief Service client to the "/controller_manager/set_hardware_component_state" service.
     *
     * Used to request activation and deactivation of harddware components.
     *
     */
    rclcpp::Client<SetHardwareComponentState>::SharedPtr hardware_state_client_;

    /**
     * @brief Timer triggered every 5 s to prune unanswered service requests
     *
     */
    rclcpp::TimerBase::SharedPtr prune_timer_;

    /**
     * @brief Map storing all joint state interface values by each joint.
     *
     */
    std::unordered_map<std::string, InterfaceValue> joint_states_;

    /**
     * @brief Map correlating hardware component name to its lifecycle_msgs/State
     *
     * Stored as NamedLifecycleState to also simply access component name from map value.
     *
     */
    std::unordered_map<std::string, NamedLifecycleState> hardware_states_;

    /**
     * @brief Map correlating controller name to its lifecycle_msgs/State
     *
     * Stored as NamedLifecycleState to also simply access controller name from map value.
     */
    std::unordered_map<std::string, NamedLifecycleState> controller_states_;

    /**
     * @brief The QT object containing all UI elements.
     *
     * Autogenerated from the "bioscara_rviz_plugin_frame.ui" file.
     *
     */
    Ui::BioscaraUI *ui_;

    /**
     * @brief callback on reported controller or hardware state changes.
     *
     * Updates the #controller_states_ and #hardware_states_ state maps.
     * Reactivates the Joint State Broadcaster if it has become inactive.
     * Updates controller and hardware state labels and buttons by invoking update_state_labels_and_btns()
     * Updates homing group state by invoking update_homing_grp_state().
     *
     * @param msg received controller states
     */
    void cm_state_callback(const ControllerManagerActivity &msg);

    /**
     * @brief callback on joint state update.
     *
     * Updates #joint_states_ with the latest values using dynamic_joint_state_msg_to_map().
     * Updates homing group state by invoking update_homing_grp_state().
     *
     * @param msg received joint states
     */
    void joint_state_callback(const DynamicJointState &msg);

    /**
     * @brief Ensure the joint state broadcaster is active.
     *
     * The JSB can become inactive, ensure that it comes active again.
     *
     * Calls the set_controller_state() method
     *
     */
    void ensure_jsb_is_active(void);

    /**
     * @brief Makes a service request to change a hardware component state.
     *
     * Request issued through the #hardware_state_client_.
     * Asynchrounous call, method exits after having issued the request.
     *
     * @param component name of hardware component to modify
     * @param target_state target state
     */
    void set_hardware_component_state(const std::string component, const lifecycle_msgs::msg::State target_state);

    /**
     * @brief Makes a service request to configure a controller state.
     *
     * Request issued through the #configure_controller_client_.
     * Asynchrounous call, method exits after having issued the request.
     *
     * @param controller name of controller to activate
     */
    void configure_controller(const std::string controller);

    /**
     * @brief Makes a service request to change controller states
     *
     * Activates and deactivates a combination of controllers.
     *
     * @param activate_controllers list of controllers to activate
     * @param deactivate_controllers list of controllers to deactivate
     * @param activate_asap if true controller switch happens in the realtime loop
     * @param timeout switch timeout
     */
    void switch_controllers(const std::vector<std::string> &activate_controllers,
                            const std::vector<std::string> &deactivate_controllers,
                            const int32_t = SwitchController::Request::BEST_EFFORT,
                            const bool activate_asap = false,
                            const builtin_interfaces::msg::Duration timeout = builtin_interfaces::msg::Duration());

    /**
     * @brief calls the correct functions to bring a controller to the correct state.
     *
     * Checks if configure_controller() needs to be called before switch_controllers()
     * can be called to bring the controller to the desired state.
     *
     * @param controller controller name
     * @param target_state target state
     */
    void set_controller_state(const std::string controller,
                              const lifecycle_msgs::msg::State target_state);

    /**
     * @brief simple conversion message type conversion function
     *
     * @param dynamic_joint_state_in message in
     * @param map_out joint states map out
     */
    void dynamic_joint_state_msg_to_map(const DynamicJointState &dynamic_joint_state_in,
                                        std::unordered_map<std::string, InterfaceValue> &map_out);

    /**
     * @brief simple conversion message type conversion function
     *
     * @param named_lcs_in NamedLifecycleState message in
     * @param map_out state map out
     */
    void named_lcs_msg_to_map(const std::vector<NamedLifecycleState> &named_lcs_in,
                              std::unordered_map<std::string, NamedLifecycleState> &map_out);

    /**
     * @brief Print life-cycle state message to console
     *
     * @param prefix string prefix
     * @param map_in map to be printed
     */
    void print_cm_map(const std::string prefix,
                      const std::unordered_map<std::string, NamedLifecycleState> &map_in);

    /**
     * @brief Prepopulates a state map with a default NamedLifecycleState for
     * every specified key.
     *
     * This is done to avoid having to check for the existence of key when
     * accessing the map. Keys could be missing if hardware interfaces are
     * not specified or named differently.
     *
     * For every joint the state interfaces are initialized as follows:
     * - *position*: 0.0
     * - *velocity*: 0.0
     * - *home*: 0.0
     *
     * Some joints (the gripper) dont have all state interfaces, but they are
     * initialized regardless.
     *
     *
     * @param state_map The state map to prepopulate
     * @param augment_vec keys that are added/overwritten
     */
    void prepopulate_joint_state_map(std::unordered_map<std::string, InterfaceValue> &state_map,
                                     std::vector<std::string> augment_vec);

    /**
     * @brief Prepopulates a state map with a default NamedLifecycleState for
     * every specified key.
     *
     * This is done to avoid having to check for the existence of key when
     * accessing the map. Keys could be missing if an expected controller or
     * hardware component has not been loaded or has a different name.
     *
     *
     * @param state_map The state map to prepopulate
     * @param augment_vec keys that are added/overwritten
     */
    void prepopulate_state_map(std::unordered_map<std::string, NamedLifecycleState> &state_map,
                               std::vector<std::string> augment_vec);

    /**
     * @brief Enabl/Disables the homing group depending on the homing controller state
     *
     */
    void update_homing_grp_state(void);

    /**
     * @brief updates all homing state labels.
     *
     * Calls set_homing_state_label() for each joint state label.
     *
     */
    void update_homing_state_labels(void);

    /**
     * @brief Set state label text and color of the homing state label.
     *
     * Sets color and text of label.
     * @param label pointer to label
     * @param state joint state
     */
    void set_homing_state_label(QLabel *label, const InterfaceValue &state);

    /**
     * @brief Update all hardware and controller state lables.
     *
     * calls update_state_label_and_btn() for each controller and hardware component.
     */
    void update_state_labels_and_btns(void);

    /**
     * @brief updates component state label and control button.
     *
     * Calls set_state_label() for state_label and set_en_btn() for en_button.
     *
     * @param state_map component state map
     * @param state_label pointer to state label
     * @param en_button pointer to enable button
     * @param state_key string key to access in state_map
     */
    void update_state_label_and_btn(
        const std::unordered_map<std::string, NamedLifecycleState> &state_map,
        QLabel *state_label,
        QPushButton *en_button,
        const std::string &state_key);

    /**
     * @brief Set the state label.
     *
     * sets color and text based on the component state.
     *
     * @param label pointer to label to modify
     * @param state state of the component
     */
    void set_state_label(QLabel *label, const NamedLifecycleState &state);

    /**
     * @brief Set the control button state
     *
     * Sets control buttons color, text and active status based on the component state.
     *
     * @param button pointer to button to modify
     * @param state state of the component
     */
    void set_en_btn(QPushButton *button, const NamedLifecycleState &state);

    /**
     * @brief Check under which conditions a component is allowed to be activated.
     *
     * Some controllers will only activate under certain conditions.
     * This functions disables the activation button if the coditions are met.
     *
     * @param component_key
     * @return true
     * @return false
     */
    bool check_activation_conditions(const std::string component_key);

    /**
     * @brief returns the next logical state from the current one.
     *
     *
     * @param current_state current state
     * @return lifecycle_msgs::msg::State
     */
    lifecycle_msgs::msg::State target_state_from_current(lifecycle_msgs::msg::State current_state);

    /**
     * @brief callback function called when a homing button is pressed
     *
     * publishes on #homing_publisher_ to initiate/stop homing
     *
     * @param joint string name of joint
     * @param cmd -1, 0, +1 to start homing to negative direction, stop homing, start homing to positve direction.
     */
    void homing_cmd(const std::string joint, const int cmd);

    /**
     * @brief callback on controller enable button
     *
     * @param controller string name of controller to change state
     */
    void ctrl_en_btn_cb(const std::string controller);

  private Q_SLOTS:

    /**
     * @brief Tries to set the bioscara_arm hardware component
     *  to the `active` state and tries to enable the velocity_joint_trajectory_controller.
     *
     */
    void arm_en_btn_cb(void);

    /**
     * @brief Tries to set the bioscara_gripper_128 hardware component
     *  to the `active` state and tries to enable the gripper_controller.
     *
     */
    void gripper_en_btn_cb(void);
  };

} // namespace bioscara_rviz_plugin

#endif // BIOSCARA_RVIZ_PANEL_HPP_
