<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>high_speed_stall_test</name>
  <version>0.0.0</version>
  <description>System Test for high speed stall detection</description>
  <maintainer email="s.storz01@gmail.com">sbstorz</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>bioscara_arm_hardware_driver</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
