name: Docs Site

on:
  push:
    branches: [ feat/restructure-dalsa-template ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: clone single_trigger_controller
        run: git clone https://github.com/DALSA-Lab/ros2_control-single_trigger_controller.git -b main lib/ros2_ws/src/dalsa_controllers/single_trigger_controller
      - name: Install Sphinx and dependencies
        run: pip install -r docs/requirements-docs.txt
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive texlive-font-utils texlive-fonts-recommended texlive-latex-extra latexmk
      - name: Generate Doxygen XML, HTML and LaTeX
        run: cd docs/doxygen && doxygen
      - name: Make doxygen PDF from LaTeX output
        run: cd docs/doxygen/latex && make
      - name: Build Sphinx HTML
        run: sphinx-build -b html docs docs/sphinx/html
      - name: Build Sphinx PDF
        run: sphinx-build -M latexpdf docs docs/sphinx/latex
      - name: Move PDFs and Doxygen HTML so that sphinx can link them
        run: mv docs/doxygen/latex/refman.pdf docs/sphinx/html/bioscara_cpp_api.pdf && mv docs/sphinx/latex/latex/bioscara.pdf docs/sphinx/html && mv docs/doxygen/html docs/sphinx/html/doxygen
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/sphinx/html
          publish_branch: gh-pages
